-- Postgres structure matching the models as of migration 0002 (no data). Generated by sqlalchemy; do not edit.
CREATE TABLE cases (
	id SERIAL NOT NULL, 
	canonical_title VARCHAR(500) NOT NULL, 
	slug VARCHAR(500) NOT NULL, 
	case_uid VARCHAR(20), 
	status VARCHAR(50) NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	summary TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	resolution_status VARCHAR(30) NOT NULL, 
	resolution_confidence FLOAT, 
	resolution_summary TEXT, 
	resolution_checked_at TIMESTAMP WITH TIME ZONE, 
	aliases_json TEXT NOT NULL, 
	people_json TEXT NOT NULL, 
	location VARCHAR(300), 
	country VARCHAR(80), 
	incident_date VARCHAR(40), 
	latest_development_date VARCHAR(40), 
	identifiers_json TEXT NOT NULL, 
	origin VARCHAR(30), 
	PRIMARY KEY (id)
);
CREATE TABLE cross_platform_funnels (
	id SERIAL NOT NULL, 
	platform VARCHAR(40) NOT NULL, 
	source_episode_id INTEGER, 
	destination_type VARCHAR(40) NOT NULL, 
	destination_url TEXT, 
	campaign_id VARCHAR(120) NOT NULL, 
	utm_source VARCHAR(120), 
	utm_campaign VARCHAR(120), 
	attribution_status VARCHAR(40) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE discovery_candidates (
	id SERIAL NOT NULL, 
	title VARCHAR(500) NOT NULL, 
	query VARCHAR(500) NOT NULL, 
	rationale TEXT NOT NULL, 
	fingerprint VARCHAR(200) NOT NULL, 
	rejected BOOLEAN NOT NULL, 
	selected BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	case_id INTEGER, 
	state VARCHAR(20) NOT NULL, 
	resolution_status VARCHAR(30) NOT NULL, 
	resolution_confidence FLOAT, 
	resolution_evidence TEXT, 
	incident_date VARCHAR(40), 
	latest_development_date VARCHAR(40), 
	location VARCHAR(300), 
	aliases_json TEXT NOT NULL, 
	people_json TEXT NOT NULL, 
	source_urls_json TEXT NOT NULL, 
	recency_score FLOAT, 
	rank_score FLOAT, 
	suggestion_reason TEXT, 
	duplicate_of_case_id INTEGER, 
	duplicate_of_candidate_id INTEGER, 
	duplicate_reason TEXT, 
	discovery_job_id INTEGER, 
	PRIMARY KEY (id)
);
CREATE TABLE monitor_runs (
	id SERIAL NOT NULL, 
	trigger VARCHAR(20) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	cases_checked INTEGER NOT NULL, 
	deep_checks INTEGER NOT NULL, 
	status_changes INTEGER NOT NULL, 
	follow_ups_created INTEGER NOT NULL, 
	search_calls INTEGER NOT NULL, 
	fetch_calls INTEGER NOT NULL, 
	llm_calls INTEGER NOT NULL, 
	error TEXT, 
	PRIMARY KEY (id)
);
CREATE TABLE music_tracks (
	id SERIAL NOT NULL, 
	track_code VARCHAR(80) NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	mood VARCHAR(30) NOT NULL, 
	variant INTEGER NOT NULL, 
	seconds FLOAT NOT NULL, 
	loop BOOLEAN NOT NULL, 
	prompt TEXT NOT NULL, 
	style VARCHAR(200), 
	provider VARCHAR(30) NOT NULL, 
	file_path TEXT, 
	characters_paid INTEGER, 
	active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE visual_audits (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	asset_code VARCHAR(20) NOT NULL, 
	key VARCHAR(64) NOT NULL, 
	sentences_json TEXT NOT NULL, 
	verdict VARCHAR(20) NOT NULL, 
	shown_as VARCHAR(20), 
	reasons_json TEXT NOT NULL, 
	detail_json TEXT NOT NULL, 
	model VARCHAR(200), 
	PRIMARY KEY (id)
);
CREATE TABLE agent_runs (
	id SERIAL NOT NULL, 
	case_id INTEGER, 
	agent_name VARCHAR(200) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	duration_ms INTEGER, 
	input_summary TEXT, 
	output_summary TEXT, 
	error TEXT, 
	provider VARCHAR(50), 
	model VARCHAR(200), 
	role VARCHAR(50), 
	temperature FLOAT, 
	fallback_used BOOLEAN NOT NULL, 
	input_tokens INTEGER, 
	output_tokens INTEGER, 
	total_tokens INTEGER, 
	estimated_cost_usd FLOAT, 
	generation_id VARCHAR(200), 
	text_hash VARCHAR(64), 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE case_status_checks (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	monitor_run_id INTEGER, 
	stage VARCHAR(10) NOT NULL, 
	outcome VARCHAR(30) NOT NULL, 
	previous_status VARCHAR(30), 
	current_status VARCHAR(30), 
	confidence FLOAT, 
	queries_json TEXT NOT NULL, 
	signals_json TEXT NOT NULL, 
	sources_json TEXT NOT NULL, 
	new_facts_json TEXT NOT NULL, 
	reason TEXT, 
	search_calls INTEGER NOT NULL, 
	fetch_calls INTEGER NOT NULL, 
	llm_calls INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE case_status_history (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	previous_status VARCHAR(30), 
	new_status VARCHAR(30) NOT NULL, 
	confidence FLOAT, 
	reason TEXT, 
	sources_json TEXT NOT NULL, 
	changed_by VARCHAR(30) NOT NULL, 
	status_check_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE case_title_candidates (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	title_norm VARCHAR(300) NOT NULL, 
	title_family_id VARCHAR(40), 
	editorial_concept TEXT, 
	generation_round INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	rejection_reason TEXT, 
	exact_collision BOOLEAN NOT NULL, 
	near_collision_score FLOAT, 
	semantic_collision_score FLOAT, 
	collision_with TEXT, 
	memorability_score FLOAT, 
	curiosity_score FLOAT, 
	specificity_score FLOAT, 
	brevity_score FLOAT, 
	sensationalism_risk FLOAT, 
	spoiler_risk FLOAT, 
	epistemic_risk FLOAT, 
	critic_json TEXT NOT NULL, 
	origin VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE contradictions (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	topic VARCHAR(500) NOT NULL, 
	description TEXT NOT NULL, 
	source_ids_json TEXT NOT NULL, 
	severity VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE episode_identities (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	case_uid VARCHAR(20), 
	episode_sequence INTEGER, 
	channel_id VARCHAR(40) NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	editorial_title VARCHAR(300), 
	resolution_status VARCHAR(30), 
	resolution_label VARCHAR(60), 
	youtube_title VARCHAR(200), 
	title_family_id VARCHAR(40), 
	thumbnail_title VARCHAR(100), 
	thumbnail_status_label VARCHAR(60), 
	host_outfit_id VARCHAR(60), 
	host_reference_asset VARCHAR(120), 
	title_approved BOOLEAN NOT NULL, 
	published BOOLEAN NOT NULL, 
	published_title VARCHAR(300), 
	published_at TIMESTAMP WITH TIME ZONE, 
	title_version INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_episode_identity UNIQUE (case_id, language), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE facts (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	claim TEXT NOT NULL, 
	original_claim TEXT, 
	original_language VARCHAR(20) NOT NULL, 
	category VARCHAR(100) NOT NULL, 
	confidence FLOAT NOT NULL, 
	source_ids_json TEXT NOT NULL, 
	disputed BOOLEAN NOT NULL, 
	event_date VARCHAR(40), 
	narrative_value VARCHAR(40), 
	evidence_strength VARCHAR(40), 
	supporting_text TEXT, 
	chunk_ids_json TEXT NOT NULL, 
	transcript_claim_ids_json TEXT NOT NULL, 
	quote_status VARCHAR(40), 
	speaker VARCHAR(300), 
	people_json TEXT NOT NULL, 
	locations_json TEXT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE follow_up_candidates (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	original_video_id INTEGER, 
	status_check_id INTEGER, 
	previous_status VARCHAR(30) NOT NULL, 
	new_status VARCHAR(30) NOT NULL, 
	development TEXT, 
	sources_json TEXT NOT NULL, 
	confidence FLOAT, 
	state VARCHAR(20) NOT NULL, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	follow_up_job_id INTEGER, 
	follow_up_video_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE host_memories (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	text TEXT NOT NULL, 
	origin VARCHAR(20) NOT NULL, 
	host_plan_id INTEGER, 
	active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE host_scenes (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	host_segments_id INTEGER NOT NULL, 
	host_segment_id VARCHAR(20) NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	channel VARCHAR(100) NOT NULL, 
	position VARCHAR(20), 
	beat_id VARCHAR(20), 
	text TEXT NOT NULL, 
	text_sha256 VARCHAR(64) NOT NULL, 
	studio_profile_id VARCHAR(50) NOT NULL, 
	studio_asset_id VARCHAR(80) NOT NULL, 
	framing_preset VARCHAR(20) NOT NULL, 
	host_position_json TEXT NOT NULL, 
	host_scale FLOAT, 
	background_mode VARCHAR(40) NOT NULL, 
	planned_start FLOAT, 
	planned_duration FLOAT, 
	voice_id VARCHAR(100), 
	voice_path VARCHAR(500), 
	voice_sha256 VARCHAR(64), 
	voice_seconds FLOAT, 
	voice_meta_json TEXT NOT NULL, 
	avatar_provider VARCHAR(30), 
	avatar_id VARCHAR(100), 
	provider_asset_id VARCHAR(100), 
	provider_asset_voice_sha VARCHAR(64), 
	provider_job_id VARCHAR(100), 
	provider_job_voice_sha VARCHAR(64), 
	provider_generation INTEGER NOT NULL, 
	avatar_video_path VARCHAR(500), 
	avatar_video_sha256 VARCHAR(64), 
	avatar_meta_json TEXT NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	failed_step VARCHAR(30), 
	last_error TEXT, 
	attempts_json TEXT NOT NULL, 
	history_json TEXT NOT NULL, 
	running_since TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE music_usages (
	id SERIAL NOT NULL, 
	track_id INTEGER, 
	case_id INTEGER NOT NULL, 
	film_key VARCHAR(60) NOT NULL, 
	production_script_id INTEGER, 
	language VARCHAR(10), 
	beat_id VARCHAR(20), 
	purpose VARCHAR(30), 
	mood VARCHAR(30), 
	start FLOAT, 
	"end" FLOAT, 
	why TEXT, 
	selection_reason TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(track_id) REFERENCES music_tracks (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE research_jobs (
	id SERIAL NOT NULL, 
	case_id INTEGER, 
	provider VARCHAR(50) NOT NULL, 
	external_job_id VARCHAR(200), 
	job_type VARCHAR(50) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	current_stage VARCHAR(60), 
	model VARCHAR(200), 
	profile VARCHAR(60), 
	input_json TEXT, 
	result_json TEXT, 
	result_summary TEXT, 
	error TEXT, 
	error_code VARCHAR(50), 
	search_calls INTEGER, 
	fetch_calls INTEGER, 
	input_tokens INTEGER, 
	output_tokens INTEGER, 
	total_tokens INTEGER, 
	model_cost_usd FLOAT, 
	search_cost_usd FLOAT, 
	fetch_cost_usd FLOAT, 
	total_cost_usd FLOAT, 
	sources_discovered INTEGER, 
	sources_accepted INTEGER, 
	sources_rejected INTEGER, 
	languages_completed TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE short_form_concepts (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	episode_identity_id INTEGER, 
	concept_type VARCHAR(60) NOT NULL, 
	source_beat_ids_json TEXT NOT NULL, 
	evidence_ids_json TEXT NOT NULL, 
	asset_ids_json TEXT NOT NULL, 
	allowed_reveals_json TEXT NOT NULL, 
	forbidden_reveals_json TEXT NOT NULL, 
	claims_json TEXT NOT NULL, 
	gate_results_json TEXT NOT NULL, 
	soft_scores_json TEXT NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE short_form_publishing_plans (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	source_episode_id INTEGER, 
	settings_json TEXT NOT NULL, 
	plan_json TEXT NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE sources (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	title VARCHAR(1000) NOT NULL, 
	url TEXT NOT NULL, 
	source_type VARCHAR(100) NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	publisher VARCHAR(500), 
	raw_text TEXT, 
	notes TEXT, 
	reliability_score FLOAT NOT NULL, 
	is_authorized_text BOOLEAN NOT NULL, 
	summary TEXT, 
	summary_en TEXT, 
	content_status VARCHAR(30) NOT NULL, 
	value_flags TEXT, 
	source_family VARCHAR(300), 
	retrieval_method VARCHAR(50), 
	retrieval_notes TEXT, 
	published_at VARCHAR(80), 
	retrieved_at TIMESTAMP WITH TIME ZONE, 
	research_provider VARCHAR(50), 
	external_reference VARCHAR(500), 
	declared_language VARCHAR(20), 
	detected_language VARCHAR(20), 
	language_confidence FLOAT, 
	language_detection_method VARCHAR(40), 
	status VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE story_versions (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	master_version_id INTEGER, 
	derived_from_master_version INTEGER, 
	narrative_angle TEXT NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	native_quality_score FLOAT, 
	semantic_consistency_score FLOAT, 
	factual_consistency_score FLOAT, 
	story_text TEXT NOT NULL, 
	engagement_score FLOAT NOT NULL, 
	similarity_score FLOAT, 
	similarity_status VARCHAR(30) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	is_best BOOLEAN NOT NULL, 
	text_hash VARCHAR(64), 
	narrative_structure TEXT, 
	critic_notes TEXT, 
	generation_provider VARCHAR(50), 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(master_version_id) REFERENCES story_versions (id)
);
CREATE TABLE thumbnails (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	brief_json TEXT NOT NULL, 
	critic_json TEXT NOT NULL, 
	layout_json TEXT NOT NULL, 
	file_path TEXT, 
	sha256 VARCHAR(64), 
	outfit_id VARCHAR(60), 
	host_asset_id VARCHAR(120), 
	primary_asset_id INTEGER, 
	secondary_asset_id INTEGER, 
	status_label VARCHAR(60), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE videos (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	production_script_id INTEGER, 
	job_id INTEGER, 
	language VARCHAR(10) NOT NULL, 
	mode VARCHAR(10) NOT NULL, 
	render_profile VARCHAR(10) NOT NULL, 
	production_type VARCHAR(20) NOT NULL, 
	original_video_id INTEGER, 
	episode_number INTEGER, 
	title VARCHAR(500), 
	youtube_title VARCHAR(200), 
	youtube_description TEXT, 
	youtube_tags_json TEXT NOT NULL, 
	status_at_production VARCHAR(30) NOT NULL, 
	status_at_publication VARCHAR(30), 
	opening_strategy VARCHAR(40), 
	file_path TEXT, 
	duration_seconds FLOAT, 
	state VARCHAR(20) NOT NULL, 
	published_at TIMESTAMP WITH TIME ZONE, 
	youtube_url TEXT, 
	metadata_json TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(original_video_id) REFERENCES videos (id)
);
CREATE TABLE visual_assets (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	asset_code VARCHAR(20) NOT NULL, 
	asset_type VARCHAR(20) NOT NULL, 
	subject_type VARCHAR(20), 
	title VARCHAR(500), 
	description TEXT, 
	entities_json TEXT NOT NULL, 
	date_start VARCHAR(20), 
	date_end VARCHAR(20), 
	location VARCHAR(300), 
	asset_role VARCHAR(20) NOT NULL, 
	story_functions_json TEXT NOT NULL, 
	provider VARCHAR(30) NOT NULL, 
	source_url TEXT, 
	page_url TEXT, 
	source_name VARCHAR(300), 
	found_for VARCHAR(300), 
	caption TEXT, 
	license VARCHAR(200), 
	credit VARCHAR(500), 
	rights_status VARCHAR(40) NOT NULL, 
	rights_reason VARCHAR(300), 
	verification_status VARCHAR(20) NOT NULL, 
	verification_confidence FLOAT, 
	verification_json TEXT, 
	quality_score FLOAT, 
	historical_accuracy_score FLOAT, 
	reveals_json TEXT NOT NULL, 
	local_path TEXT, 
	thumbnail_path TEXT, 
	width INTEGER, 
	height INTEGER, 
	phash VARCHAR(32), 
	sha256 VARCHAR(64), 
	duration_seconds FLOAT, 
	has_original_audio BOOLEAN NOT NULL, 
	original_audio_language VARCHAR(10), 
	spec_json TEXT, 
	human_override BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	relevance_tier INTEGER, 
	case_relevance VARCHAR(30), 
	entity_key VARCHAR(120), 
	entity_type VARCHAR(30), 
	found_during VARCHAR(30), 
	clip_start FLOAT, 
	clip_end FLOAT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE TABLE claim_clusters (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	canonical_claim_en TEXT NOT NULL, 
	member_claim_ids_json TEXT NOT NULL, 
	independent_source_family_count INTEGER NOT NULL, 
	languages_json TEXT NOT NULL, 
	claim_type VARCHAR(60) NOT NULL, 
	narrative_value VARCHAR(40), 
	support_status VARCHAR(40) NOT NULL, 
	confidence FLOAT NOT NULL, 
	promoted_fact_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(promoted_fact_id) REFERENCES facts (id)
);
CREATE TABLE documentary_jobs (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	master_version_id INTEGER, 
	mode VARCHAR(10) NOT NULL, 
	languages_json TEXT NOT NULL, 
	pilot_seconds FLOAT, 
	render_profile VARCHAR(20) NOT NULL, 
	refresh_visuals BOOLEAN NOT NULL, 
	from_zero BOOLEAN NOT NULL, 
	target_minutes FLOAT, 
	batch_id VARCHAR(40), 
	status VARCHAR(20) NOT NULL, 
	stage VARCHAR(60), 
	progress FLOAT NOT NULL, 
	stages_json TEXT NOT NULL, 
	result_json TEXT NOT NULL, 
	error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	production_type VARCHAR(20) NOT NULL, 
	follow_up_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(master_version_id) REFERENCES story_versions (id)
);
CREATE TABLE editorial_blueprints (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	evidence_fingerprint VARCHAR(32), 
	story_text_hash VARCHAR(64), 
	central_question TEXT, 
	editorial_thesis TEXT, 
	human_thread TEXT, 
	blueprint_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_provider VARCHAR(50), 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(story_version_id) REFERENCES story_versions (id)
);
CREATE TABLE media_usages (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	asset_id INTEGER NOT NULL, 
	production_script_id INTEGER, 
	film_key VARCHAR(60), 
	language VARCHAR(10), 
	shot_index INTEGER, 
	beat_id VARCHAR(20), 
	start FLOAT, 
	"end" FLOAT, 
	seconds FLOAT, 
	kind VARCHAR(20), 
	tier INTEGER, 
	sentence TEXT, 
	reason TEXT, 
	appearance INTEGER NOT NULL, 
	repeat_justified BOOLEAN, 
	repeat_reason TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(asset_id) REFERENCES visual_assets (id)
);
CREATE TABLE original_media_segments (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	asset_id INTEGER NOT NULL, 
	beat_id VARCHAR(20), 
	source_start FLOAT NOT NULL, 
	source_end FLOAT NOT NULL, 
	language VARCHAR(10), 
	transcript TEXT, 
	story_use TEXT, 
	translation_strategy_json TEXT NOT NULL, 
	selected BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(asset_id) REFERENCES visual_assets (id)
);
CREATE TABLE production_scripts (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	blueprint_id INTEGER, 
	visual_plan_id INTEGER, 
	version INTEGER NOT NULL, 
	mode VARCHAR(10) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	duration_seconds FLOAT, 
	script_json TEXT NOT NULL, 
	critique_json TEXT, 
	audit_json TEXT, 
	render_json TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(story_version_id) REFERENCES story_versions (id)
);
CREATE TABLE research_queries (
	id SERIAL NOT NULL, 
	research_job_id INTEGER NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	query_text TEXT NOT NULL, 
	purpose VARCHAR(60), 
	priority VARCHAR(20), 
	round INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(research_job_id) REFERENCES research_jobs (id)
);
CREATE TABLE short_form_scripts (
	id SERIAL NOT NULL, 
	concept_id INTEGER NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	hook TEXT NOT NULL, 
	body TEXT NOT NULL, 
	cta TEXT NOT NULL, 
	target_duration FLOAT NOT NULL, 
	visual_requirements_json TEXT NOT NULL, 
	original_audio_opportunity_json TEXT NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(concept_id) REFERENCES short_form_concepts (id)
);
CREATE TABLE source_chunks (
	id SERIAL NOT NULL, 
	source_id INTEGER NOT NULL, 
	chunk_index INTEGER NOT NULL, 
	text TEXT NOT NULL, 
	token_count INTEGER NOT NULL, 
	section_title VARCHAR(500), 
	page_or_location VARCHAR(200), 
	content_hash VARCHAR(64) NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_id) REFERENCES sources (id)
);
CREATE TABLE video_sources (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	source_id INTEGER, 
	platform VARCHAR(50) NOT NULL, 
	video_id VARCHAR(100) NOT NULL, 
	url TEXT NOT NULL, 
	title VARCHAR(1000) NOT NULL, 
	channel_name VARCHAR(500), 
	channel_url TEXT, 
	language VARCHAR(20) NOT NULL, 
	published_at VARCHAR(80), 
	duration_seconds INTEGER, 
	view_count INTEGER, 
	description TEXT, 
	discovery_query VARCHAR(500), 
	research_language VARCHAR(20), 
	transcript_status VARCHAR(40) NOT NULL, 
	transcript_type VARCHAR(40), 
	classification VARCHAR(60) NOT NULL, 
	source_independence VARCHAR(40) NOT NULL, 
	likely_derivative_of INTEGER, 
	creator_source_family VARCHAR(300), 
	duplicate_group VARCHAR(200), 
	relevance_score FLOAT, 
	novel_information_ratio FLOAT, 
	value_score FLOAT, 
	extraction_cache_key VARCHAR(80), 
	processed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(source_id) REFERENCES sources (id)
);
CREATE TABLE voice_performances (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	performance_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(story_version_id) REFERENCES story_versions (id)
);
CREATE TABLE audio_plans (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	plan_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_provider VARCHAR(50), 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id)
);
CREATE TABLE chapter_plans (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	languages_json TEXT NOT NULL, 
	plan_json TEXT NOT NULL, 
	audit_json TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id)
);
CREATE TABLE epistemic_contract_sets (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	coverage_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_epistemic_contract_set UNIQUE (case_id, story_version_id, version), 
	CONSTRAINT ck_epistemic_contract_set_status CHECK (status IN ('draft', 'in_review', 'approved', 'invalid')), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id), 
	FOREIGN KEY(story_version_id) REFERENCES story_versions (id)
);
CREATE TABLE host_plans (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	plan_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id)
);
CREATE TABLE narrative_insights (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	video_source_id INTEGER, 
	insight_type VARCHAR(60) NOT NULL, 
	text_original TEXT, 
	canonical_text_en TEXT NOT NULL, 
	segment_ids_json TEXT NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(video_source_id) REFERENCES video_sources (id)
);
CREATE TABLE platform_variants (
	id SERIAL NOT NULL, 
	concept_id INTEGER NOT NULL, 
	script_id INTEGER, 
	platform VARCHAR(40) NOT NULL, 
	language VARCHAR(10) NOT NULL, 
	hook TEXT NOT NULL, 
	caption TEXT NOT NULL, 
	description TEXT NOT NULL, 
	cta TEXT NOT NULL, 
	end_card TEXT NOT NULL, 
	subtitle_layout_json TEXT NOT NULL, 
	cover_frame_json TEXT NOT NULL, 
	duration FLOAT, 
	destination_json TEXT NOT NULL, 
	disclosure_flags_json TEXT NOT NULL, 
	rights_flags_json TEXT NOT NULL, 
	policy_flags_json TEXT NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(concept_id) REFERENCES short_form_concepts (id), 
	FOREIGN KEY(script_id) REFERENCES short_form_scripts (id)
);
CREATE TABLE research_results (
	id SERIAL NOT NULL, 
	research_query_id INTEGER, 
	url TEXT NOT NULL, 
	canonical_url VARCHAR(1000), 
	final_url TEXT, 
	title VARCHAR(1000), 
	snippet TEXT, 
	rank INTEGER, 
	provider VARCHAR(50) NOT NULL, 
	model VARCHAR(200), 
	result_language VARCHAR(20), 
	relevance_score FLOAT, 
	credibility_score FLOAT, 
	novelty_score FLOAT, 
	fetch_status VARCHAR(30), 
	accepted BOOLEAN NOT NULL, 
	rejection_reason VARCHAR(60), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(research_query_id) REFERENCES research_queries (id)
);
CREATE TABLE reveal_graphs (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	validation_json TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_reveal_graph_version UNIQUE (case_id, blueprint_id, version), 
	CONSTRAINT ck_reveal_graph_status CHECK (status IN ('draft', 'validated', 'invalid')), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id)
);
CREATE TABLE transcript_claims (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	video_source_id INTEGER NOT NULL, 
	segment_ids_json TEXT NOT NULL, 
	original_language VARCHAR(20) NOT NULL, 
	original_claim TEXT, 
	canonical_claim_en TEXT NOT NULL, 
	claim_type VARCHAR(60) NOT NULL, 
	confidence FLOAT NOT NULL, 
	certainty VARCHAR(40) NOT NULL, 
	speaker VARCHAR(300), 
	quote_classification VARCHAR(40), 
	timestamp_start FLOAT, 
	timestamp_end FLOAT, 
	verification_status VARCHAR(40) NOT NULL, 
	supporting_source_ids_json TEXT NOT NULL, 
	cluster_id INTEGER, 
	promoted_fact_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(video_source_id) REFERENCES video_sources (id), 
	FOREIGN KEY(cluster_id) REFERENCES claim_clusters (id), 
	FOREIGN KEY(promoted_fact_id) REFERENCES facts (id)
);
CREATE TABLE transcript_segments (
	id SERIAL NOT NULL, 
	video_source_id INTEGER NOT NULL, 
	start_seconds FLOAT NOT NULL, 
	end_seconds FLOAT NOT NULL, 
	segment_index INTEGER NOT NULL, 
	text_original TEXT NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	canonical_text_en TEXT, 
	content_hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(video_source_id) REFERENCES video_sources (id)
);
CREATE TABLE visual_plans (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	blueprint_id INTEGER NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	requirements_json TEXT NOT NULL, 
	plan_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(blueprint_id) REFERENCES editorial_blueprints (id)
);
CREATE TABLE epistemic_claims (
	id SERIAL NOT NULL, 
	contract_set_id INTEGER NOT NULL, 
	claim_key VARCHAR(120) NOT NULL, 
	claim_text TEXT NOT NULL, 
	source_sentence_text TEXT, 
	span_start INTEGER, 
	span_end INTEGER, 
	beat_id VARCHAR(20) NOT NULL, 
	modality VARCHAR(40) NOT NULL, 
	assertion_role VARCHAR(40) NOT NULL, 
	speaker VARCHAR(300), 
	parent_claim_key VARCHAR(120), 
	source_refs_json TEXT NOT NULL, 
	evidence_refs_json TEXT NOT NULL, 
	review_status VARCHAR(20) NOT NULL, 
	reviewer_notes TEXT, 
	origin VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_epistemic_claim_key UNIQUE (contract_set_id, claim_key), 
	CONSTRAINT ck_epistemic_claim_modality CHECK (modality IN ('ESTABLISHED', 'BELIEVED_BY_INVESTIGATORS', 'ALLEGED', 'ABSENCE_OF_EVIDENCE', 'DISPUTED')), 
	CONSTRAINT ck_epistemic_claim_review_status CHECK (review_status IN ('proposed', 'approved', 'rejected')), 
	FOREIGN KEY(contract_set_id) REFERENCES epistemic_contract_sets (id)
);
CREATE TABLE host_segments (
	id SERIAL NOT NULL, 
	case_id INTEGER NOT NULL, 
	story_version_id INTEGER NOT NULL, 
	host_plan_id INTEGER NOT NULL, 
	language VARCHAR(20) NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	segments_json TEXT NOT NULL, 
	validation_json TEXT NOT NULL, 
	generation_model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	FOREIGN KEY(story_version_id) REFERENCES story_versions (id), 
	FOREIGN KEY(host_plan_id) REFERENCES host_plans (id)
);
CREATE TABLE research_source_links (
	id SERIAL NOT NULL, 
	research_result_id INTEGER NOT NULL, 
	source_id INTEGER NOT NULL, 
	relationship VARCHAR(40) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(research_result_id) REFERENCES research_results (id), 
	FOREIGN KEY(source_id) REFERENCES sources (id)
);
CREATE TABLE reveal_nodes (
	id SERIAL NOT NULL, 
	graph_id INTEGER NOT NULL, 
	node_key VARCHAR(120) NOT NULL, 
	label VARCHAR(500) NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	first_revealed_beat_id VARCHAR(20) NOT NULL, 
	first_revealed_order INTEGER NOT NULL, 
	first_revealed_at_seconds FLOAT, 
	description TEXT, 
	metadata_json TEXT NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_reveal_node_key UNIQUE (graph_id, node_key), 
	FOREIGN KEY(graph_id) REFERENCES reveal_graphs (id)
);
CREATE TABLE short_form_metrics (
	id SERIAL NOT NULL, 
	variant_id INTEGER, 
	platform VARCHAR(40) NOT NULL, 
	metric_date VARCHAR(40), 
	views INTEGER NOT NULL, 
	unique_viewers INTEGER, 
	average_watch_time FLOAT, 
	completion_rate FLOAT, 
	rewatches INTEGER, 
	likes INTEGER NOT NULL, 
	comments INTEGER NOT NULL, 
	shares INTEGER NOT NULL, 
	saves INTEGER NOT NULL, 
	profile_visits INTEGER, 
	link_clicks INTEGER, 
	youtube_clicks INTEGER, 
	new_subscribers INTEGER, 
	destination_clicks INTEGER, 
	youtube_episode_visits INTEGER, 
	estimated_conversion_rate FLOAT, 
	attribution_status VARCHAR(40) NOT NULL, 
	raw_json TEXT NOT NULL, 
	detail_json TEXT NOT NULL, 
	model VARCHAR(200), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(variant_id) REFERENCES platform_variants (id)
);
CREATE TABLE reveal_asset_links (
	id SERIAL NOT NULL, 
	graph_id INTEGER NOT NULL, 
	node_id INTEGER NOT NULL, 
	visual_asset_id INTEGER, 
	original_media_segment_id INTEGER, 
	asset_kind VARCHAR(20) NOT NULL, 
	note TEXT, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_reveal_asset_target CHECK (visual_asset_id IS NOT NULL OR original_media_segment_id IS NOT NULL), 
	CONSTRAINT ck_reveal_asset_kind CHECK (asset_kind IN ('visual', 'audio')), 
	FOREIGN KEY(graph_id) REFERENCES reveal_graphs (id), 
	FOREIGN KEY(node_id) REFERENCES reveal_nodes (id), 
	FOREIGN KEY(visual_asset_id) REFERENCES visual_assets (id), 
	FOREIGN KEY(original_media_segment_id) REFERENCES original_media_segments (id)
);
CREATE TABLE reveal_edges (
	id SERIAL NOT NULL, 
	graph_id INTEGER NOT NULL, 
	prerequisite_node_id INTEGER NOT NULL, 
	dependent_node_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_reveal_edge UNIQUE (graph_id, prerequisite_node_id, dependent_node_id), 
	CONSTRAINT ck_reveal_no_self_edge CHECK (prerequisite_node_id != dependent_node_id), 
	FOREIGN KEY(graph_id) REFERENCES reveal_graphs (id), 
	FOREIGN KEY(prerequisite_node_id) REFERENCES reveal_nodes (id), 
	FOREIGN KEY(dependent_node_id) REFERENCES reveal_nodes (id)
);
CREATE TABLE reveal_exposures (
	id SERIAL NOT NULL, 
	graph_id INTEGER NOT NULL, 
	beat_id VARCHAR(20) NOT NULL, 
	node_id INTEGER NOT NULL, 
	exposure_type VARCHAR(20) NOT NULL, 
	source_field VARCHAR(30) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_reveal_exposure UNIQUE (graph_id, beat_id, node_id), 
	CONSTRAINT ck_reveal_exposure_type CHECK (exposure_type IN ('exposed', 'withheld')), 
	FOREIGN KEY(graph_id) REFERENCES reveal_graphs (id), 
	FOREIGN KEY(node_id) REFERENCES reveal_nodes (id)
);
CREATE INDEX ix_cases_canonical_title ON cases (canonical_title);
CREATE INDEX ix_cases_case_uid ON cases (case_uid);
CREATE INDEX ix_cases_resolution_status ON cases (resolution_status);
CREATE UNIQUE INDEX ix_cases_slug ON cases (slug);
CREATE UNIQUE INDEX ux_cases_case_uid ON cases (case_uid);
CREATE INDEX ix_cross_platform_funnels_attribution_status ON cross_platform_funnels (attribution_status);
CREATE INDEX ix_cross_platform_funnels_campaign_id ON cross_platform_funnels (campaign_id);
CREATE INDEX ix_cross_platform_funnels_platform ON cross_platform_funnels (platform);
CREATE INDEX ix_cross_platform_funnels_source_episode_id ON cross_platform_funnels (source_episode_id);
CREATE INDEX ix_discovery_candidates_case_id ON discovery_candidates (case_id);
CREATE INDEX ix_discovery_candidates_fingerprint ON discovery_candidates (fingerprint);
CREATE INDEX ix_discovery_candidates_state ON discovery_candidates (state);
CREATE INDEX ix_discovery_candidates_title ON discovery_candidates (title);
CREATE INDEX ix_monitor_runs_status ON monitor_runs (status);
CREATE INDEX ix_music_tracks_kind ON music_tracks (kind);
CREATE INDEX ix_music_tracks_mood ON music_tracks (mood);
CREATE UNIQUE INDEX ix_music_tracks_track_code ON music_tracks (track_code);
CREATE INDEX ix_visual_audits_asset_code ON visual_audits (asset_code);
CREATE INDEX ix_visual_audits_case_id ON visual_audits (case_id);
CREATE UNIQUE INDEX ix_visual_audits_key ON visual_audits (key);
CREATE INDEX ix_agent_runs_agent_name ON agent_runs (agent_name);
CREATE INDEX ix_agent_runs_case_id ON agent_runs (case_id);
CREATE INDEX ix_agent_runs_status ON agent_runs (status);
CREATE INDEX ix_case_status_checks_case_id ON case_status_checks (case_id);
CREATE INDEX ix_case_status_checks_monitor_run_id ON case_status_checks (monitor_run_id);
CREATE INDEX ix_case_status_history_case_id ON case_status_history (case_id);
CREATE INDEX ix_case_title_candidates_case_id ON case_title_candidates (case_id);
CREATE INDEX ix_case_title_candidates_language ON case_title_candidates (language);
CREATE INDEX ix_case_title_candidates_status ON case_title_candidates (status);
CREATE INDEX ix_case_title_candidates_title_family_id ON case_title_candidates (title_family_id);
CREATE INDEX ix_case_title_candidates_title_norm ON case_title_candidates (title_norm);
CREATE INDEX ix_contradictions_case_id ON contradictions (case_id);
CREATE INDEX ix_episode_identities_case_id ON episode_identities (case_id);
CREATE INDEX ix_episode_identities_case_uid ON episode_identities (case_uid);
CREATE INDEX ix_episode_identities_title_family_id ON episode_identities (title_family_id);
CREATE INDEX ix_facts_case_id ON facts (case_id);
CREATE INDEX ix_follow_up_candidates_case_id ON follow_up_candidates (case_id);
CREATE INDEX ix_follow_up_candidates_state ON follow_up_candidates (state);
CREATE INDEX ix_host_memories_case_id ON host_memories (case_id);
CREATE INDEX ix_host_memories_host_plan_id ON host_memories (host_plan_id);
CREATE INDEX ix_host_memories_kind ON host_memories (kind);
CREATE INDEX ix_host_scenes_case_id ON host_scenes (case_id);
CREATE INDEX ix_host_scenes_host_segments_id ON host_scenes (host_segments_id);
CREATE INDEX ix_host_scenes_language ON host_scenes (language);
CREATE INDEX ix_host_scenes_status ON host_scenes (status);
CREATE INDEX ix_host_scenes_story_version_id ON host_scenes (story_version_id);
CREATE INDEX ix_music_usages_case_id ON music_usages (case_id);
CREATE INDEX ix_music_usages_film_key ON music_usages (film_key);
CREATE INDEX ix_music_usages_track_id ON music_usages (track_id);
CREATE INDEX ix_research_jobs_case_id ON research_jobs (case_id);
CREATE INDEX ix_research_jobs_job_type ON research_jobs (job_type);
CREATE INDEX ix_research_jobs_status ON research_jobs (status);
CREATE INDEX ix_short_form_concepts_case_id ON short_form_concepts (case_id);
CREATE INDEX ix_short_form_concepts_concept_type ON short_form_concepts (concept_type);
CREATE INDEX ix_short_form_concepts_episode_identity_id ON short_form_concepts (episode_identity_id);
CREATE INDEX ix_short_form_concepts_status ON short_form_concepts (status);
CREATE INDEX ix_short_form_publishing_plans_case_id ON short_form_publishing_plans (case_id);
CREATE INDEX ix_short_form_publishing_plans_source_episode_id ON short_form_publishing_plans (source_episode_id);
CREATE INDEX ix_short_form_publishing_plans_status ON short_form_publishing_plans (status);
CREATE INDEX ix_sources_case_id ON sources (case_id);
CREATE INDEX ix_story_versions_case_id ON story_versions (case_id);
CREATE INDEX ix_story_versions_status ON story_versions (status);
CREATE INDEX ix_thumbnails_case_id ON thumbnails (case_id);
CREATE INDEX ix_thumbnails_language ON thumbnails (language);
CREATE INDEX ix_thumbnails_status ON thumbnails (status);
CREATE INDEX ix_videos_case_id ON videos (case_id);
CREATE INDEX ix_videos_original_video_id ON videos (original_video_id);
CREATE INDEX ix_videos_production_script_id ON videos (production_script_id);
CREATE INDEX ix_videos_state ON videos (state);
CREATE INDEX ix_visual_assets_asset_code ON visual_assets (asset_code);
CREATE INDEX ix_visual_assets_asset_role ON visual_assets (asset_role);
CREATE INDEX ix_visual_assets_asset_type ON visual_assets (asset_type);
CREATE INDEX ix_visual_assets_case_id ON visual_assets (case_id);
CREATE INDEX ix_visual_assets_entity_key ON visual_assets (entity_key);
CREATE INDEX ix_visual_assets_phash ON visual_assets (phash);
CREATE INDEX ix_visual_assets_rights_status ON visual_assets (rights_status);
CREATE INDEX ix_visual_assets_sha256 ON visual_assets (sha256);
CREATE INDEX ix_visual_assets_verification_status ON visual_assets (verification_status);
CREATE INDEX ix_claim_clusters_case_id ON claim_clusters (case_id);
CREATE INDEX ix_documentary_jobs_batch_id ON documentary_jobs (batch_id);
CREATE INDEX ix_documentary_jobs_case_id ON documentary_jobs (case_id);
CREATE INDEX ix_documentary_jobs_status ON documentary_jobs (status);
CREATE INDEX ix_editorial_blueprints_case_id ON editorial_blueprints (case_id);
CREATE INDEX ix_editorial_blueprints_status ON editorial_blueprints (status);
CREATE INDEX ix_editorial_blueprints_story_version_id ON editorial_blueprints (story_version_id);
CREATE INDEX ix_media_usages_asset_id ON media_usages (asset_id);
CREATE INDEX ix_media_usages_case_id ON media_usages (case_id);
CREATE INDEX ix_media_usages_film_key ON media_usages (film_key);
CREATE INDEX ix_media_usages_production_script_id ON media_usages (production_script_id);
CREATE INDEX ix_original_media_segments_asset_id ON original_media_segments (asset_id);
CREATE INDEX ix_original_media_segments_case_id ON original_media_segments (case_id);
CREATE INDEX ix_production_scripts_case_id ON production_scripts (case_id);
CREATE INDEX ix_production_scripts_language ON production_scripts (language);
CREATE INDEX ix_production_scripts_status ON production_scripts (status);
CREATE INDEX ix_production_scripts_story_version_id ON production_scripts (story_version_id);
CREATE INDEX ix_research_queries_research_job_id ON research_queries (research_job_id);
CREATE INDEX ix_short_form_scripts_concept_id ON short_form_scripts (concept_id);
CREATE INDEX ix_short_form_scripts_language ON short_form_scripts (language);
CREATE INDEX ix_short_form_scripts_status ON short_form_scripts (status);
CREATE INDEX ix_source_chunks_content_hash ON source_chunks (content_hash);
CREATE INDEX ix_source_chunks_source_id ON source_chunks (source_id);
CREATE INDEX ix_video_sources_case_id ON video_sources (case_id);
CREATE INDEX ix_video_sources_extraction_cache_key ON video_sources (extraction_cache_key);
CREATE INDEX ix_video_sources_source_id ON video_sources (source_id);
CREATE INDEX ix_video_sources_transcript_status ON video_sources (transcript_status);
CREATE INDEX ix_video_sources_video_id ON video_sources (video_id);
CREATE INDEX ix_voice_performances_case_id ON voice_performances (case_id);
CREATE INDEX ix_voice_performances_status ON voice_performances (status);
CREATE INDEX ix_voice_performances_story_version_id ON voice_performances (story_version_id);
CREATE INDEX ix_audio_plans_blueprint_id ON audio_plans (blueprint_id);
CREATE INDEX ix_audio_plans_case_id ON audio_plans (case_id);
CREATE INDEX ix_audio_plans_status ON audio_plans (status);
CREATE INDEX ix_chapter_plans_blueprint_id ON chapter_plans (blueprint_id);
CREATE INDEX ix_chapter_plans_case_id ON chapter_plans (case_id);
CREATE INDEX ix_chapter_plans_status ON chapter_plans (status);
CREATE INDEX ix_epistemic_contract_sets_blueprint_id ON epistemic_contract_sets (blueprint_id);
CREATE INDEX ix_epistemic_contract_sets_case_id ON epistemic_contract_sets (case_id);
CREATE INDEX ix_epistemic_contract_sets_status ON epistemic_contract_sets (status);
CREATE INDEX ix_epistemic_contract_sets_story_version_id ON epistemic_contract_sets (story_version_id);
CREATE INDEX ix_host_plans_blueprint_id ON host_plans (blueprint_id);
CREATE INDEX ix_host_plans_case_id ON host_plans (case_id);
CREATE INDEX ix_host_plans_status ON host_plans (status);
CREATE INDEX ix_narrative_insights_case_id ON narrative_insights (case_id);
CREATE INDEX ix_narrative_insights_video_source_id ON narrative_insights (video_source_id);
CREATE INDEX ix_platform_variants_concept_id ON platform_variants (concept_id);
CREATE INDEX ix_platform_variants_language ON platform_variants (language);
CREATE INDEX ix_platform_variants_platform ON platform_variants (platform);
CREATE INDEX ix_platform_variants_script_id ON platform_variants (script_id);
CREATE INDEX ix_platform_variants_status ON platform_variants (status);
CREATE INDEX ix_research_results_research_query_id ON research_results (research_query_id);
CREATE INDEX ix_reveal_graphs_blueprint_id ON reveal_graphs (blueprint_id);
CREATE INDEX ix_reveal_graphs_case_id ON reveal_graphs (case_id);
CREATE INDEX ix_reveal_graphs_status ON reveal_graphs (status);
CREATE INDEX ix_transcript_claims_case_id ON transcript_claims (case_id);
CREATE INDEX ix_transcript_claims_cluster_id ON transcript_claims (cluster_id);
CREATE INDEX ix_transcript_claims_verification_status ON transcript_claims (verification_status);
CREATE INDEX ix_transcript_claims_video_source_id ON transcript_claims (video_source_id);
CREATE INDEX ix_transcript_segments_content_hash ON transcript_segments (content_hash);
CREATE INDEX ix_transcript_segments_video_source_id ON transcript_segments (video_source_id);
CREATE INDEX ix_visual_plans_blueprint_id ON visual_plans (blueprint_id);
CREATE INDEX ix_visual_plans_case_id ON visual_plans (case_id);
CREATE INDEX ix_visual_plans_status ON visual_plans (status);
CREATE INDEX ix_epistemic_claims_assertion_role ON epistemic_claims (assertion_role);
CREATE INDEX ix_epistemic_claims_beat_id ON epistemic_claims (beat_id);
CREATE INDEX ix_epistemic_claims_contract_set_id ON epistemic_claims (contract_set_id);
CREATE INDEX ix_epistemic_claims_modality ON epistemic_claims (modality);
CREATE INDEX ix_epistemic_claims_parent_claim_key ON epistemic_claims (parent_claim_key);
CREATE INDEX ix_epistemic_claims_review_status ON epistemic_claims (review_status);
CREATE INDEX ix_host_segments_case_id ON host_segments (case_id);
CREATE INDEX ix_host_segments_host_plan_id ON host_segments (host_plan_id);
CREATE INDEX ix_host_segments_language ON host_segments (language);
CREATE INDEX ix_host_segments_status ON host_segments (status);
CREATE INDEX ix_host_segments_story_version_id ON host_segments (story_version_id);
CREATE INDEX ix_research_source_links_research_result_id ON research_source_links (research_result_id);
CREATE INDEX ix_research_source_links_source_id ON research_source_links (source_id);
CREATE INDEX ix_reveal_nodes_category ON reveal_nodes (category);
CREATE INDEX ix_reveal_nodes_graph_id ON reveal_nodes (graph_id);
CREATE INDEX ix_short_form_metrics_attribution_status ON short_form_metrics (attribution_status);
CREATE INDEX ix_short_form_metrics_metric_date ON short_form_metrics (metric_date);
CREATE INDEX ix_short_form_metrics_platform ON short_form_metrics (platform);
CREATE INDEX ix_short_form_metrics_variant_id ON short_form_metrics (variant_id);
CREATE INDEX ix_reveal_asset_links_graph_id ON reveal_asset_links (graph_id);
CREATE INDEX ix_reveal_asset_links_node_id ON reveal_asset_links (node_id);
CREATE INDEX ix_reveal_asset_links_original_media_segment_id ON reveal_asset_links (original_media_segment_id);
CREATE INDEX ix_reveal_asset_links_visual_asset_id ON reveal_asset_links (visual_asset_id);
CREATE INDEX ix_reveal_edges_dependent_node_id ON reveal_edges (dependent_node_id);
CREATE INDEX ix_reveal_edges_graph_id ON reveal_edges (graph_id);
CREATE INDEX ix_reveal_edges_prerequisite_node_id ON reveal_edges (prerequisite_node_id);
CREATE INDEX ix_reveal_exposures_beat_id ON reveal_exposures (beat_id);
CREATE INDEX ix_reveal_exposures_graph_id ON reveal_exposures (graph_id);
CREATE INDEX ix_reveal_exposures_node_id ON reveal_exposures (node_id);
