"""Which real case pictures may appear on a thumbnail.

Found media is not automatically publishable. Every asset passes hard
gates (real, verified for this case, rights, resolution, no spoiler, no
graphic content, no unsupported guilt); survivors are ranked by what they
show: victim/person, suspect (only when guilt is established), key object,
location, document, then context."""

from __future__ import annotations

import json

from sqlalchemy.orm import Session

from app.core.ai_config import ai_config
from app.db.models import Case, EditorialBlueprint, VisualAsset
from app.documentary import storage
from app.documentary.visuals import rights as R
from app.documentary.visuals.spoilers import revealed_by, shows_custody

IMAGE_TYPES = {"photo", "image"}


def _json(text, default):
    try:
        return json.loads(text) if text else default
    except (TypeError, ValueError):
        return default


def late_reveal_ids(db: Session, case_id: int) -> set[str]:
    row = (db.query(EditorialBlueprint)
           .filter(EditorialBlueprint.case_id == case_id, EditorialBlueprint.status != "invalid")
           .order_by(EditorialBlueprint.id.desc()).first())
    beats = _json(row.blueprint_json, {}).get("beats", []) if row else []
    n = ai_config.thumbnail.opening_beats
    return {str(r) for b in beats[n:] for r in (b.get("reveals") or [])}


def asset_kind(a: VisualAsset) -> str:
    """victim | suspect | person | object | place | document | other."""
    ver = _json(a.verification_json, {})
    kind = str(ver.get("subject_type") or a.entity_type or a.subject_type or "other").lower()
    role = (a.asset_role or "").lower()
    if kind == "person" and role in ("victim", "suspect"):
        return role
    return kind if kind in ai_config.thumbnail.subject_priority else (
        "place" if kind in ("landscape", "building", "map") else "other")


def reject_reason(db_case: Case, a: VisualAsset, late_ids: set[str], may_state_guilt: bool
                  ) -> str | None:
    cfg = ai_config.thumbnail
    if a.case_id != db_case.id:
        return "belongs to another case"
    if a.asset_type not in IMAGE_TYPES:
        return f"not a still image ({a.asset_type})"
    if a.provider == "generated" or a.found_during == "generated":
        return "generated by the app, not a real case picture"
    if a.verification_status != "verified" or (a.verification_confidence or 0) < \
            cfg.min_verification_confidence:
        return "not verified for this case"
    ver = _json(a.verification_json, {})
    if str(ver.get("matches_claim", "yes")).lower() in ("no", "false"):
        return "verification says it does not match the case"
    if a.relevance_tier is not None and a.relevance_tier >= 5:
        return "generic atmosphere picture, not case-specific"
    rs = a.rights_status or "unknown"
    if rs == "do_not_use":
        return "rights: do_not_use"
    if not R.allowed(rs, cfg.rights_profile):
        if not (cfg.allow_editorial_override and a.human_override):
            return f"rights: {rs} (needs editorial approval)"
    if not a.local_path or not storage.resolve(a.local_path).exists():
        return "file missing"
    if (a.width or 0) < cfg.min_image_px[0] or (a.height or 0) < cfg.min_image_px[1]:
        return f"resolution too low ({a.width}x{a.height})"
    if revealed_by(a) & late_ids:
        return "shows something the story reveals later (spoiler)"
    if shows_custody(a):
        return "shows custody or court (spoils the outcome)"
    seen = " ".join(str(x or "") for x in (a.description, a.caption, ver.get("depicts"))).lower()
    if any(t in seen for t in cfg.graphic_terms):
        return "graphic content"
    if asset_kind(a) == "suspect" and not may_state_guilt:
        return "suspect picture while responsibility is not established"
    return None


def rank_assets(db: Session, case: Case, *, may_state_guilt: bool | None = None
                ) -> tuple[list[dict], list[dict]]:
    """(accepted ranked best first, rejected with reasons)."""
    if may_state_guilt is None:
        may_state_guilt = (case.resolution_status or "") == "SOLVED"
    late = late_reveal_ids(db, case.id)
    pri = ai_config.thumbnail.subject_priority
    ok, bad = [], []
    for a in db.query(VisualAsset).filter(VisualAsset.case_id == case.id).all():
        why = reject_reason(case, a, late, may_state_guilt)
        info = {"asset": a, "id": a.id, "code": a.asset_code, "kind": asset_kind(a)}
        if why:
            bad.append({**info, "reason": why})
        else:
            ok.append(info)
    ok.sort(key=lambda i: (pri.get(i["kind"], 9), i["asset"].relevance_tier or 4,
                           -(i["asset"].quality_score or 0), i["id"]))
    return ok, bad


def pair_refusal(primary: dict, secondary: dict, may_state_guilt: bool) -> str | None:
    people = {"victim", "suspect", "person"}
    kinds = {primary["kind"], secondary["kind"]}
    if primary["kind"] in people and secondary["kind"] in people:
        if kinds == {"victim", "suspect"} and not may_state_guilt:
            return ("two faces framed as victim and suspect while responsibility is not "
                    "established (misleading relationship)")
        if not (may_state_guilt and kinds == {"victim", "suspect"}):
            return "two people on one thumbnail imply a relationship"
    return None
