"""Rights classification (Part 23). FOUND does not mean USABLE.

Deterministic, explainable rules on provider metadata and domain:
  owned / licensed           -> user uploads and our own generated cards/maps
  public_domain              -> PD / CC0 licenses (e.g. Wikimedia Commons)
  creative_commons           -> CC BY / BY-SA (attribution required)
  editorial_review_required  -> news and case-source images (may be usable
                                as editorial reporting; a human decides)
  permission_required        -> explicit "all rights reserved" / NC / ND
  do_not_use                 -> stock libraries, watermarks
  unknown                    -> anything else
"""

from __future__ import annotations

import re
from urllib.parse import urlparse

from app.core.ai_config import ai_config

RIGHTS = ("owned", "licensed", "public_domain", "creative_commons",
          "editorial_review_required", "permission_required", "unknown",
          "do_not_use")


def _domain(url: str | None) -> str:
    try:
        return (urlparse(url or "").hostname or "").lower()
    except ValueError:
        return ""


def classify(provider: str, license_name: str | None = None,
             url: str | None = None, page_url: str | None = None,
             watermark: bool = False) -> tuple[str, str]:
    """(rights_status, reason)."""
    blocked = ai_config.visual_search.blocked_domains
    for u in (url, page_url):
        d = _domain(u)
        if d and any(b in d for b in blocked):
            return "do_not_use", f"stock library ({d})"
    if watermark:
        return "do_not_use", "watermark visible"
    if provider in ("upload", "owned"):
        return "owned", "uploaded by the production"
    if provider == "generated":
        return "owned", "generated by the app (map data credited separately)"
    lic = (license_name or "").strip().lower()
    if lic:
        if re.search(r"\b(nc|nd)\b|non-?commercial|no ?deriv", lic):
            return "permission_required", f"license restricts use ({license_name})"
        if re.search(r"public domain|\bpd\b|cc0|pdm", lic):
            return "public_domain", f"license: {license_name}"
        if re.search(r"\bcc\b|creative commons|cc-by|by-sa|\bby\b", lic):
            return "creative_commons", f"license: {license_name}"
        if "all rights reserved" in lic or "copyright" in lic:
            return "permission_required", f"license: {license_name}"
    if provider == "source_page":
        return ("editorial_review_required",
                f"image from a case source ({_domain(page_url or url)})")
    return "unknown", "no license information"


def allowed(rights_status: str, profile: str | None = None) -> bool:
    profile = profile or ai_config.render.profile
    return rights_status in ai_config.rights.allowed_for_render.get(profile, [])


def needs_attribution(rights_status: str) -> bool:
    return rights_status in ai_config.rights.attribution_required
